document.write( '		<main>\n' );
document.write( '			<div class=\"frame\">\n' );
document.write( '				</header>\n' );
document.write( '			</div>\n' );
document.write( '			<div class=\"slideshow\">\n' );
document.write( '				<div class=\"slideshow__deco\"></div>\n' );
document.write( '				<div class=\"slide\">\n' );
document.write( '					<div class=\"slide__img-wrap\">\n' );
document.write( '						<div class=\"slide__img\" style=\"background-image: url(https://media.gettyimages.com/photos/beautiful-woman-picture-id175521756?k=6&m=175521756&s=612x612&w=0&h=GfNAIyN_awLMC4GCQB3I5y1k3eYh797INkjrG0JuVhs=);\"></div>\n' );
document.write( '					</div>\n' );
document.write( '					<div class=\"slide__side\">Memories & Thoughts</div>\n' );
document.write( '					<div class=\"slide__title-wrap\">\n' );
document.write( '						<span class=\"slide__number\">1</span>\n' );
document.write( '						<h3 class=\"slide__title\">Automation</h3>\n' );
document.write( '						<h4 class=\"slide__subtitle\">A tree needs to be your friend if you\'re going to paint him</h4>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '				<div class=\"slide\">\n' );
document.write( '					<div class=\"slide__img-wrap\">\n' );
document.write( '						<div class=\"slide__img\" style=\"background-image: url(https://media.gettyimages.com/photos/beautiful-woman-with-jewelry-picture-id181861826?k=6&m=181861826&s=612x612&w=0&h=ZfQvh9sFHj3Ch1u68JlBj3WVnx5VfsKeYlRqVIOx50Y=);\"></div>\n' );
document.write( '					</div>\n' );
document.write( '					<div class=\"slide__side\">Random Roam</div>\n' );
document.write( '					<div class=\"slide__title-wrap\">\n' );
document.write( '						<span class=\"slide__number\">2</span>\n' );
document.write( '						<h3 class=\"slide__title\">Machines</h3>\n' );
document.write( '						<h4 class=\"slide__subtitle\">This is probably the greatest thing to happen in my life</h4>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '				<div class=\"slide\">\n' );
document.write( '					<div class=\"slide__img-wrap\">\n' );
document.write( '						<div class=\"slide__img\" style=\"background-image: url(https://media.gettyimages.com/photos/cateye-make-up-picture-id471920237?k=6&m=471920237&s=612x612&w=0&h=HK1k01dTvqMQIrLRdAzeHSN_GJUjURLJw2JGCFYW4Kc=);\"></div>\n' );
document.write( '					</div>\n' );
document.write( '					<div class=\"slide__side\">Arbitrary Words</div>\n' );
document.write( '					<div class=\"slide__title-wrap\">\n' );
document.write( '						<span class=\"slide__number\">3</span>\n' );
document.write( '						<h3 class=\"slide__title\">Coexistence</h3>\n' );
document.write( '						<h4 class=\"slide__subtitle\">The only guide is your heart</h4>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '				<div class=\"slide\">\n' );
document.write( '					<div class=\"slide__img-wrap\">\n' );
document.write( '						<div class=\"slide__img\" style=\"background-image: url(https://media.gettyimages.com/photos/sensual-blonde-woman-picture-id465353265?k=6&m=465353265&s=612x612&w=0&h=uUCxYoZSDR7ia1p9UUUMayTGZ8sPSFzBzHu4ph7pTUw=);\"></div>\n' );
document.write( '					</div>\n' );
document.write( '					<div class=\"slide__side\">Haunted Drift</div>\n' );
document.write( '					<div class=\"slide__title-wrap\">\n' );
document.write( '						<span class=\"slide__number\">4</span>\n' );
document.write( '						<h3 class=\"slide__title\">Bellamio</h3>\n' );
document.write( '						<h4 class=\"slide__subtitle\">The only prerequisite is that it makes you happy</h4>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '				<div class=\"slide\">\n' );
document.write( '					<div class=\"slide__img-wrap\">\n' );
document.write( '						<div class=\"slide__img\" style=\"background-image: url(https://media.gettyimages.com/photos/beautiful-diva-picture-id187890220?k=6&m=187890220&s=612x612&w=0&h=I9wlaiTLV6-OiOHNI_FNUWp9L-HXtLEriSQPiJqFi5s=);\"></div>\n' );
document.write( '					</div>\n' );
document.write( '					<div class=\"slide__side\">Fun Diverge</div>\n' );
document.write( '					<div class=\"slide__title-wrap\">\n' );
document.write( '						<span class=\"slide__number\">5</span>\n' );
document.write( '						<h3 class=\"slide__title\">Pastures</h3>\n' );
document.write( '						<h4 class=\"slide__subtitle\">Let\'s go up in here, and start having some fun</h4>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '				<div class=\"slide\">\n' );
document.write( '					<div class=\"slide__img-wrap\">\n' );
document.write( '						<div class=\"slide__img\" style=\"background-image: url(https://media.gettyimages.com/photos/sensual-blonde-woman-picture-id466016465?s=2048x2048);\"></div>\n' );
document.write( '					</div>\n' );
document.write( '					<div class=\"slide__side\">Hopes & Dreams</div>\n' );
document.write( '					<div class=\"slide__title-wrap\">\n' );
document.write( '						<span class=\"slide__number\">6</span>\n' );
document.write( '						<h3 class=\"slide__title\">Focus</h3>\n' );
document.write( '						<h4 class=\"slide__subtitle\">This is unplanned it really just happens</h4>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '				<button class=\"nav nav--prev\">\n' );
document.write( '					<svg class=\"icon icon--navarrow-prev\">\n' );
document.write( '						<use xlink:href=\"#icon-navarrow\"></use>\n' );
document.write( '					</svg>\n' );
document.write( '				</button>\n' );
document.write( '				<button class=\"nav nav--next\">\n' );
document.write( '					<svg class=\"icon icon--navarrow-next\">\n' );
document.write( '						<use xlink:href=\"#icon-navarrow\"></use>\n' );
document.write( '					</svg>\n' );
document.write( '				</button>\n' );
document.write( '			</div>\n' );
document.write( '			<div class=\"content\">\n' );
document.write( '				<div class=\"content__item\">\n' );
document.write( '					<span class=\"content__number\">1</span>\n' );
document.write( '					<h3 class=\"content__title\">Automation</h3>\n' );
document.write( '					<h4 class=\"content__subtitle\">A tree needs to be your friend if you\'re going to paint him</h4>\n' );
document.write( '					<div class=\"content__text\">Just let this happen. We just let this flow right out of our minds. Just relax and let it flow. That easy. Let\'s put some happy little clouds in our world. It\'s a very cold picture, I may have to go get my coat. It’s about to freeze me to death. This is gonna be a happy little seascape. Let\'s go up in here, and start having some fun The least little bit can do so much. Work on one thing at a time. Don\'t get carried away - we have plenty of time. Put your feelings into it, your heart, it\'s your world. These trees are so much fun. I get started on them and I have a hard time stopping.</div>\n' );
document.write( '				</div>\n' );
document.write( '				<div class=\"content__item\">\n' );
document.write( '					<span class=\"content__number\">2</span>\n' );
document.write( '					<h3 class=\"content__title\">Machines</h3>\n' );
document.write( '					<h4 class=\"content__subtitle\">This is probably the greatest thing to happen in my life</h4>\n' );
document.write( '					<div class=\"content__text\">We\'re not trying to teach you a thing to copy. We\'re just here to teach you a technique, then let you loose into the world. Now, we\'re going to fluff this cloud. We don\'t have anything but happy trees here. Let\'s do that again. Use what you see, don\'t plan it. Let\'s go up in here, and start having some fun The least little bit can do so much. Work on one thing at a time. Don\'t get carried away - we have plenty of time. Put your feelings into it, your heart, it\'s your world. These trees are so much fun. I get started on them and I have a hard time stopping.</div>\n' );
document.write( '				</div>\n' );
document.write( '				<div class=\"content__item\">\n' );
document.write( '					<span class=\"content__number\">3</span>\n' );
document.write( '					<h3 class=\"content__title\">Coexistence</h3>\n' );
document.write( '					<h4 class=\"content__subtitle\">The only guide is your heart</h4>\n' );
document.write( '					<div class=\"content__text\">Let\'s go up in here, and start having some fun The least little bit can do so much. Work on one thing at a time. Don\'t get carried away - we have plenty of time. Put your feelings into it, your heart, it\'s your world. These trees are so much fun. I get started on them and I have a hard time stopping. But we\'re not there yet, so we don\'t need to worry about it. Now let\'s put some happy little clouds in here. What the devil. A thin paint will stick to a thick paint. I\'m going to mix up a little color. </div>\n' );
document.write( '				</div>\n' );
document.write( '				<div class=\"content__item\">\n' );
document.write( '					<span class=\"content__number\">4</span>\n' );
document.write( '					<h3 class=\"content__title\">Bellamio</h3>\n' );
document.write( '					<h4 class=\"content__subtitle\">The only prerequisite is that it makes you happy</h4>\n' );
document.write( '					<div class=\"content__text\">See. We take the corner of the brush and let it play back-and-forth. This is unplanned it really just happens. I\'m sort of a softy, I couldn\'t shoot Bambi except with a camera. I guess I\'m a little weird. I like to talk to trees and animals. That\'s okay though; I have more fun than most people. We\'ll play with clouds today. Didn\'t you know you had that much power? You can move mountains. You can do anything. Let\'s go up in here, and start having some fun The least little bit can do so much. Work on one thing at a time. Don\'t get carried away - we have plenty of time. Put your feelings into it, your heart, it\'s your world. These trees are so much fun. I get started on them and I have a hard time stopping.</div>\n' );
document.write( '				</div>\n' );
document.write( '				<div class=\"content__item\">\n' );
document.write( '					<span class=\"content__number\">5</span>\n' );
document.write( '					<h3 class=\"content__title\">Pastures</h3>\n' );
document.write( '					<h4 class=\"content__subtitle\">Let\'s go up in here, and start having some fun</h4>\n' );
document.write( '					<div class=\"content__text\">So often we avoid running water, and running water is a lot of fun. Everyone is going to see things differently - and that\'s the way it should be. A big strong tree needs big strong roots. Steve wants reflections, so let\'s give him reflections. We don\'t have to be committed. We are just playing here. Making all those little fluffies that live in the clouds. Let\'s go up in here, and start having some fun The least little bit can do so much. Work on one thing at a time. Don\'t get carried away - we have plenty of time. Put your feelings into it, your heart, it\'s your world. These trees are so much fun. I get started on them and I have a hard time stopping.</div>\n' );
document.write( '				</div>\n' );
document.write( '				<div class=\"content__item\">\n' );
document.write( '					<span class=\"content__number\">6</span>\n' );
document.write( '					<h3 class=\"content__title\">Focus</h3>\n' );
document.write( '					<h4 class=\"content__subtitle\">This is unplanned it really just happens</h4>\n' );
document.write( '					<div class=\"content__text\">But we\'re not there yet, so we don\'t need to worry about it. Now let\'s put some happy little clouds in here. What the devil. A thin paint will stick to a thick paint. I\'m going to mix up a little color. We’ll use Van Dyke Brown, Permanent Red, and a little bit of Prussian Blue. Let\'s go up in here, and start having some fun The least little bit can do so much. Work on one thing at a time. Don\'t get carried away - we have plenty of time. Put your feelings into it, your heart, it\'s your world. These trees are so much fun. I get started on them and I have a hard time stopping.</div>\n' );
document.write( '				</div>\n' );
document.write( '				<button class=\"content__close\">\n' );
document.write( '					<svg class=\"icon icon--longarrow\">\n' );
document.write( '						<use xlink:href=\"#icon-longarrow\"></use>\n' );
document.write( '					</svg>\n' );
document.write( '				</button>\n' );
document.write( '			</div>\n' );
document.write( '		</main>\n' );

